version: "3.1"
    
services:

    mysql:
      image: mysql:${MYSQL_VERSION:-8.0.22}
      command: [ "--default-authentication-plugin=mysql_native_password" ]
      ports:
        - "${MYSQL_PORT:-3306}:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-very_secret}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-xampp_db}
        MYSQL_USER: ${MYSQL_USER:-xampp_user}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      restart: unless-stopped
      networks:
        - shared_network
      volumes:
        - db-data:/var/lib/mysql

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${NGINX_PORT:-80}:80"
        - 443:443
      depends_on:
        - php-fpm
      restart: unless-stopped
      networks:
        - shared_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.9
        depends_on:
          - mysql
        ports:
          - "10003:80"
        environment:
          - PMA_HOST=xampp-db
        volumes:
          - /sessions
          - ./docker/phpmyadmin/save/:/var/www/phpmyadmin/save/
          - ./docker/phpmyadmin/upload/:/var/www/phpmyadmin/upload/
          - ./docker/phpmyadmin/config.php:/etc/phpmyadmin/config.user.inc.php
        restart: unless-stopped
        networks:
          - shared_network
          
    php-fpm:
      build:
        context: ./docker/php-fpm
        dockerfile: Dockerfile
      working_dir: /application
      depends_on:
        - mysql
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      restart: unless-stopped
      networks:
        - shared_network
          
volumes:
  db-data:
    driver: local

networks:
  shared_network:
    driver: bridge
